### ISSUE TITLE
When running openknx on Multicast address 224.0.23.12  it reports a  'unhandled serviceType' for 2 types

### ISSUE THREAD

**Issue by felsnerino** [iobroker-community-adapters/ioBroker.openknx#170]
**Describe the bug**  
When running the openknx modul on the multicast adress, it works in general fine (thanks a lot again). It seems only to have a problem with a paket that is "read KNXNetHeader: unhandled serviceType = SEARCH_REQUEST".
Log excerpt:
openknx.0 | 2022-04-03 16:44:34.022 | warn | [warn] 2022-04-03 14:44:34.022 read KNXNetHeader: unhandled serviceType = SEARCH_REQUEST
openknx.0 | 2022-04-03 16:44:34.020 | warn | [warn] 2022-04-03 14:44:34.020 read KNXNetHeader: unhandled serviceType = undefined

**To Reproduce**  
I guess it depends on the "other" KNX IP devices you have. I am running with IP Router for 3 Main Lines. A Timberwolf server and an Eibport. Not sure who generates these service types.

**Expected behavior**  
I guess we could ignore them, as the IOBroker is not expected as such to anounce itself.

**Screenshots & Logfiles**  
Log excerpt:
openknx.0 | 2022-04-03 16:44:34.022 | warn | [warn] 2022-04-03 14:44:34.022 read KNXNetHeader: unhandled serviceType = SEARCH_REQUEST
openknx.0 | 2022-04-03 16:44:34.020 | warn | [warn] 2022-04-03 14:44:34.020 read KNXNetHeader: unhandled serviceType = undefined

Logentries are every ~3 seconds.

**Versions:**  
 - Adapter version: 0.1.25 (installed from GitHub)
 - JS-Controller version: 4.0.21
 - Node version: v14.19.0
 - Operating system: 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

**Additional context**  
not sure what to add... if shall do a wireshark, etc. please let me know. Again, appreciate a lot the efforts for the open.knx adapter!!

**Comment by boellner** [comment]
Do you experience any misbehaviour, or is it noly the warning that bothers?
It is not implemented in the actual used knx lib. My plan is to switch in a few month to a new one that handles this message type

**Comment by felsnerino** [comment]
I think, it can be ignored, and I have not experienced any problems. The messages are processed, values are updated. Everything seems fine, as far as I can tell...

**Comment by Missenberger79** [comment]
with multicast i get warn end error logs:


openknx.0 | 2022-04-16 13:39:19.396 | error | [error] 2022-04-16 11:39:19.395 (idle): Incomplete/unparseable UDP packet: TypeError: Cannot read property 'service_type' of undefined at datagramDesc (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:286:55) at fsm.FSM.onUdpSocketMessage (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:21:19) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/IpRoutingConnection.js:57:14) at Socket.emit (events.js:400:28) at Socket.emit (domain.js:475:12) at UDP.onMessage (dgram.js:931:8): 06100530001729050c0311006ebcd011ae2b0c020080ff
-- | -- | -- | --
openknx.0 | 2022-04-16 13:39:19.394 | warn | [warn] 2022-04-16 11:39:19.394 read KNXNetHeader: unhandled serviceType = undefined

i can write to knx but the status doesn´t work 
adapter version 0.1.24

**Comment by boellner** [comment]
I dont posses a KNX IP router. Until then this issue must be on hold

**Comment by felsnerino** [comment]
I noticed, that the packages will be generated from the ETS Application itself (if not running, they are not visible). So I assume, if you would configure the/your respective multicast KNX adress AND have the ETS5/6 application started at the same time in the same subnetwork of the IObroker you would see those packages (at least I assume)... I guess that is how the ETS at the end shows all available/configured KNX Devices that have an IP interface.

**Comment by felsnerino** [comment]
Will this be fixed at some point? It is not critical... just a bit annoying... I understand that other things are more important but maybe it is also not a big deal, or will be fixed automatically with the other KNX Library?

**Comment by boellner** [comment]
A SEARCH_REQUEST is issued by this adapter for example in the admin menu to discover knx interfaces.
Or by the ETS if it is commanded to look for interfaces.
I didn't discover issues with tunneling connections. 

Im neglecting now the SEARCH_REQUEST since they are not meant for IOB.

openknx.0 | 2022-04-03 16:44:34.020 | warn | [warn] 2022-04-03 14:44:34.020 read KNXNetHeader: unhandled serviceType = undefined

Unclear what undefined is, since it is not known by the knx lib. 
Mybe its the newer SearchRequestExtended 
-> add this to the lib, and create a more verbose error message on unknown service type

**Comment by mcm1957** [comment]
Issue seems to be outdated.

If the problem still exists with current release (1.0.0) please open a new issue
