### ISSUE TITLE
Unhandled promise rejection: Cannot read properties of undefined (reading 'init')

### ISSUE THREAD

**Issue by Skae86** [iobroker-community-adapters/ioBroker.openknx#322]
**Describe the bug**  
Updated from v0.3.2 to v0.4.0
Adapter does not start anymore. Errors, see log file.

**Versions:**  
 - Adapter version: 0.4.0
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Linux (Raspberry Pi 4)

**Workaround** 
Downgrade to v0.3.2

**Logfile**  
2022-12-16 21:31:14.501 - silly: openknx.0 (23102) statesDB connected
2022-12-16 21:31:14.551 - debug: openknx.0 (23102) Plugin sentry Initialize Plugin (enabled=true)
2022-12-16 21:31:14.898 - info: openknx.0 (23102) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.openknx, node: v16.17.0, js-controller: 4.0.23
2022-12-16 21:31:14.932 - error: openknx.0 (23102) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-16 21:31:14.933 - error: openknx.0 (23102) unhandled promise rejection: Cannot read properties of undefined (reading 'init')
2022-12-16 21:31:15.152 - error: openknx.0 (23102) TypeError: Cannot read properties of undefined (reading 'init')
at openknx.onReady (/opt/iobroker/node_modules/iobroker.openknx/main.js:82:33)
at openknx.emit (node:events:513:28)
at openknx.emit (node:domain:489:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26
2022-12-16 21:31:15.153 - error: openknx.0 (23102) Cannot read properties of undefined (reading 'init')
2022-12-16 21:31:15.176 - info: openknx.0 (23102) terminating
2022-12-16 21:31:15.177 - debug: openknx.0 (23102) Plugin sentry destroyed
2022-12-16 21:31:15.178 - warn: openknx.0 (23102) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-12-16 21:31:15.189 - silly: openknx.0 (23102) States system redis pmessage system.adapter.openknx.0.logLevel/system.adapter.openknx.0.logLevel:{"val":"silly","ack":true,"ts":1671222675172,"q":0,"from":"system.adapter.openknx.0","lc":1671222583481}
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'init')
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[1]: at openknx.onReady (/opt/iobroker/node_modules/iobroker.openknx/main.js:82:33)
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[1]: at openknx.emit (node:events:513:28)
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[1]: at openknx.emit (node:domain:489:12)
2022-12-16 21:31:15.731 - error: host.raspberrypi4-iob Caught by controller[1]: at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26
2022-12-16 21:31:15.732 - error: host.raspberrypi4-iob instance system.adapter.openknx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-12-16 21:31:15.732 - info: host.raspberrypi4-iob Restart adapter system.adapter.openknx.0 because enabled
2022-12-16 21:31:15.732 - warn: host.raspberrypi4-iob Do not restart adapter system.adapter.openknx.0 because restart loop detected
2022-12-16 21:31:21.661 - info: host.raspberrypi4-iob "system.adapter.openknx.0" disabled

**Comment by boellner** [comment]
fixed in 0.4.1 please check

**Comment by Skae86** [comment]
Works now. Thanks.
