### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by woehrer12** [iobroker-community-adapters/ioBroker.openknx#346]
the adapter does not start

2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: internal/modules/cjs/loader.js:905
--
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]:   throw err;
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]:   ^
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: Error: Cannot find module 'binary-parser'
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: Require stack:
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/KnxProtocol.js
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js
2023-03-12 08:33:03.368  - error: host.IOBrokerVM Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.openknx/lib/knx/index.js
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.openknx/main.js
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:101:18)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Object. (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/KnxProtocol.js:8:16)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:950:32)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:974:19) {
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:   requireStack: [
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/KnxProtocol.js',
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js',
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.openknx/lib/knx/index.js',
2023-03-12 08:33:03.369  - error: host.IOBrokerVM Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.openknx/main.js'
2023-03-12 08:33:03.370  - error: host.IOBrokerVM Caught by controller[0]:   ]
2023-03-12 08:33:03.370  - error: host.IOBrokerVM Caught by controller[0]: }
2023-03-12 08:33:03.370  - error: host.IOBrokerVM instance system.adapter.openknx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Versions:**  
 - Adapter version: v0.2.5
 - JS-Controller version: 4.0.24
 - Node version: v14.21.3
 - Operating system: linux

**Comment by Apollon77** [comment]
Please rteinstall the adapter

**Comment by boellner** [comment]
or
npm install binary-parser
