### ISSUE TITLE
Incomplete/unparseable UDP packet

### ISSUE THREAD

**Issue by Horgul123** [iobroker-community-adapters/ioBroker.openknx#497]
MDT MDT SCN-IP000.02
Proxmox 8.02 auf LEnovo Tiny M910q
js-controller 6.0.9
node 20.15.1
OpenKNX 0.9.0

(auch getestet mit einer neuen iobroker Version auf einem 2. Server (gleiche Hardware, gleiche Proxmox Version) mit iobroker Neuistallation aus dem stable Release)

Die Verbindung wird aufgebaut, nach kurzer Zeit kommen aber solche Fehler.
Ich habe auch mit dem iobroker.knx ähnliche Probleme.

Kann jemand erkennen, was diese Fehler auslösen könnte?

`[error] 2024-07-22 05:14:29.622 (idle): Incomplete/unparseable UDP packet: RangeError: Offset is outside the bounds of the DataView at DataView.getUint16 (<anonymous>) at Parser.eval [as compiled] (eval at compile (/opt/iobroker/node_modules/binary-parser/lib/binary_parser.ts:842:21), <anonymous>:9:18) at Parser.parse (/opt/iobroker/node_modules/binary-parser/lib/binary_parser.ts:906:17) at CustomProtocolReader.<anonymous> (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/KnxProtocol.js:380:45) at CustomProtocolReader.ProtocolReader$prepend [as prepend] (/opt/iobroker/node_modules/binary-protocol/lib/reader.js:108:6) at CustomProtocolReader.ProtocolReader$process [as process] (/opt/iobroker/node_modules/binary-protocol/lib/reader.js:310:12) at CustomProtocolReader.ProtocolReader$next [as next] (/opt/iobroker/node_modules/binary-protocol/lib/reader.js:234:19) at fsm.FSM.onUdpSocketMessage (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:21:23) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/IpTunnelingConnection.js:32:14) at Socket.emit (node:events:519:28): 061004200014042049002900b060310131050080`

ein tcpdump liefert folgendes:

`oliver@iobrokervm:~$ sudo tcpdump -vvv "udp and src 192.168.0.112"
tcpdump: listening on ens18, link-type EN10MB (Ethernet), snapshot length 262144 bytes
08:03:03.469902 IP (tos 0x0, ttl 255, id 666, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:05.471549 IP (tos 0x0, ttl 255, id 667, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:07.473776 IP (tos 0x0, ttl 255, id 668, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:09.475543 IP (tos 0x0, ttl 255, id 669, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:11.467625 IP (tos 0x0, ttl 255, id 670, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:13.469607 IP (tos 0x0, ttl 255, id 671, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:15.471283 IP (tos 0x0, ttl 255, id 672, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:17.472986 IP (tos 0x0, ttl 255, id 673, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:19.474454 IP (tos 0x0, ttl 255, id 674, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
08:03:21.469337 IP (tos 0x0, ttl 255, id 675, offset 0, flags [none], proto UDP (17), length 36)
    KNX.fritz.box.3671 > iobrokervm.fritz.box.57620: [udp sum ok] UDP, length 8
`

**Comment by Horgul123** [comment]
Problem (anscheinend) gelöst:
Nachdem ich wirklich alles andere ausgeschlossen habe (hab sogar ne neue IP Schnittstelle geholt), habe ich mal nur die Busspannungsversorgung und das Interface angeschlossen.
Kein Fehler mehr!
Hab dann nach und nach die einzelnen Bereiche vom KNX Bus wieder angeschlossen.
Weiterhin kein Fehler mehr.

Ich versteh es nicht. Die Busspannungsversorgung hatte ich auch mehrfach abgeschaltet, das war also nicht das Problem. Irgendwas KNX Seitig muss die IP Interfaces gestört haben..
