### ISSUE TITLE
Catch Exception correctly

### ISSUE THREAD

**Issue by TA2k** [iobroker-community-adapters/ioBroker.openknx#86]
[debug] 2022-01-10 19:45:41.902 initializing private connection to 192.168.188.38

Error: Interface 192.168.188.80 not found or has no useful IPv4 address!
    at fsm.getLocalAddress (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/FSM.js:617:15)
    at fsm.IpTunnelingConnection.instance.Connect (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/IpTunnelingConnection.js:26:30)
    at Object.Connection (/opt/iobroker/node_modules/iobroker.openknx/lib/knx/src/Connection.js:324:36)
    at openknx.startKnxStack (/opt/iobroker/node_modules/iobroker.openknx/main.js:358:34)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.openknx/main.js:539:26)
    at processImmediate (internal/timers.js:466:21)

**Comment by boellner** [comment]
how to reproduce this error?

**Comment by TA2k** [comment]
Don't know. Please catch the error.

**Comment by DutchmanNL** [comment]
should be solved by merging PR https://github.com/iobroker-community-adapters/ioBroker.openknx/pull/88
